window.flickrplaces = {
 "Eirunepe, Brazil": "/Brazil/Amazonas/Eirunep%C3%A9", 
 "Blantyre, Malawi": "/Malawi/Blantyre/Blantyre", 
 "Nairobi, Kenya": "/Kenya/Nairobi+Area/Nairobi", 
 "Menominee, United States": "/United+States/Michigan/Menominee", 
 "Cordoba, Argentina": "/Argentina/Cordoba/C%C3%B3rdoba", 
 "Mariehamn, Aland Islands": "/Aland+Islands/Mariehamn/Maarianhamina", 
 "Manaus, Brazil": "/Brazil/Amazonas/Manaus", 
 "DumontDUrville, Antarctica": "/Antarctica", 
 "McMurdo, Antarctica": "/Antarctica", 
 "Adak, United States": "/United+States/Alaska/Adak", 
 "Kwajalein, Marshall Islands": "/Marshall+Islands", 
 "Athens, Greece": "/Greece/Attiki/Athens", 
 "Sao Tome, Sao Tome and Principe": "/Sao+Tome+and+Principe/Sao+Tome/S%C3%A3o+Tom%C3%A9", 
 "Antananarivo, Madagascar": "/Madagascar/Antananarivo/Antananarivo", 
 "Port Moresby, Papua New Guinea": "/Papua+New+Guinea/National+Capital/Port+Moresby", 
 "Cayenne, French Guiana": "/French+Guiana/Cayenne/Cayenne", 
 "Riyadh, Saudi Arabia": "/Saudi+Arabia/Ar+Riyad/Riyadh", 
 "Mazatlan, Mexico": "/Mexico/Sinaloa/Mazatl%C3%A1n", 
 "Belem, Brazil": "/Brazil/Para/Bel%C3%A9m", 
 "Belgrade, Serbia": "/Serbia/Beograd/Beograd", 
 "Douala, Cameroon": "/Cameroon/Littoral/Douala", 
 "Hong Kong, HK": "/Hong+Kong/Hong+Kong+Island/%E9%A6%99%E6%B8%AF", 
 "Macquarie, Antarctica": "/Antarctica", 
 "Kralendijk, Bonaire, Saint Eustatius and Saba ": "/Netherlands+Antilles/Bonaire/Kralendijk", 
 "Tarawa, Kiribati": "/Kiribati/Bairiki", 
 "Tunis, Tunisia": "/Tunisia/Tunis/Tunis", 
 "Copenhagen, Denmark": "/Denmark/Hovedstaden/K%C3%B8benhavn", 
 "Saipan, Northern Mariana Islands": "/Northern+Mariana+Islands/Saipan/Saipan", 
 "New York, United States": "/United+States/New+York/New+York", 
 "Karachi, Pakistan": "/Pakistan/Sindh/Karachi", 
 "Montevideo, Uruguay": "/Uruguay/Montevideo/Montevideo", 
 "Louisville, Kentucky": "/United+States/Kentucky/Louisville", 
 "Riga, Latvia": "/Latvia/Riga/R%C4%ABga", 
 "Thule, Greenland": "/Greenland/Nordgronland/Thule", 
 "Dar es Salaam, Tanzania": "/Tanzania/Dar+es+Salaam/Dar+es+Salaam", 
 "Azores, Portugal": "/Portugal/Azores", 
 "Yerevan, Armenia": "/Armenia/Yerevan/Yerevan", 
 "Uzhgorod, Ukraine": "/Ukraine/Zakarpattia+Oblast/Uzhhorod", 
 "Jersey, JE": "/United+Kingdom/Channel+Islands", 
 "Skopje, Macedonia": "/Macedonia/Skopje", 
 "Dominica, DM": "/Dominica", 
 "Monticello, Kentucky": "/United+States/Kentucky/Monticello", 
 "Cancun, Mexico": "/Mexico/Quintana+Roo/Canc%C3%BAn", 
 "Hermosillo, Mexico": "/Mexico/Sonora/Hermosillo", 
 "Rarotonga, Cook Islands": "/Cook+Islands", 
 "Ceuta, Spain": "/Spain/Ceuta+Province/Ceuta", 
 "Atikokan, Canada": "/Canada/Ontario/Atikokan", 
 "Port-au-Prince, Haiti": "/Haiti/Ouest/Port-au-Prince", 
 "Center, North Dakota": "/United+States/North+Dakota/Center", 
 "Lindeman, Australia": "/Australia/Queensland", 
 "Brussels, Belgium": "/Belgium/Capital+Region+of+Brussels/Bruxelles", 
 "Montserrat, MS": "/Montserrat", 
 "Pohnpei, Micronesia": "/Federated+States+of+Micronesia/Pohnpei", 
 "Recife, Brazil": "/Brazil/Pernambuco/Recife", 
 "Sitka, United States": "/United+States/Alaska/Sitka/in-City+and+Borough+of+Sitka", 
 "Honolulu, United States": "/United+States/Hawaii/Honolulu", 
 "Phnom Penh, Cambodia": "/Cambodia/Phnum+Penh/Phnom+Penh", 
 "Addis Ababa, Ethiopia": "/Ethiopia/Addis+Ababa/Addis+Ababa", 
 "Petersburg, Indiana": "/United+States/Indiana/Petersburg", 
 "Palmer, Antarctica": "/Antarctica", 
 "Guernsey, GG": "/United+Kingdom/Channel+Islands", 
 "Indianapolis, Indiana": "/United+States/Indiana/Indianapolis", 
 "Tell City, Indiana": "/United+States/Indiana/Tell+City", 
 "Marengo, Indiana": "/United+States/Indiana/Marengo", 
 "St Barthelemy, Saint Barth\u00e9lemy": "/Switzerland/Canton+of+Vaud/St.-Barth%C3%A9lemy", 
 "Cayman, Cayman Islands": "/Cayman+Islands", 
 "Simferopol, Ukraine": "/Ukraine/Crimea/Simferopol%27", 
 "Creston, Canada": "/Canada/British+Columbia/Creston", 
 "Araguaina, Brazil": "/Brazil/Tocantins/Aragua%C3%ADna", 
 "Tortola, British Virgin Islands": "/British+Virgin+Islands", 
 "Qyzylorda, Kazakhstan": "/Kazakhstan/Qyzylorda/Qyzylorda", 
 "Novokuznetsk, Russia": "/Russia/Kemerovskaya+Oblast/Novokuznetsk", 
 "Chongqing, China": "/China/Chongqing", 
 "Tallinn, Estonia": "/Estonia/Harju+County/Tallinn", 
 "Tongatapu, Tonga": "/Tonga/Tongatapu", 
 "Fiji, FJ": "/Fiji", 
 "Oslo, Norway": "/Norway/Oslo+Fylke/Oslo", 
 "Danmarkshavn, Greenland": "/Greenland", 
 "Kosrae, Micronesia": "/Federated+States+of+Micronesia/Kosrae", 
 "Canary, Spain": "/Spain", 
 "Ho Chi Minh, Vietnam": "/Vietnam/Ho+Chi+Minh/Th%C3%A0nh+Ph%E1%BB%91+H%E1%BB%93+Ch%C3%AD+Minh", 
 "La Rioja, Argentina": "/Argentina/La+Rioja/La+Rioja", 
 "Banjul, Gambia": "/The+Gambia/Banjul/Banjul", 
 "Ulaanbaatar, Mongolia": "/Mongolia/Ulaanbaatar/Ulan+Bator", 
 "Beirut, Lebanon": "/Lebanon/Bayrut/Beirut", 
 "Casablanca, Morocco": "/Morocco/Casablanca/Casablanca", 
 "Luanda, Angola": "/Angola/Luanda/Luanda", 
 "Guadeloupe, GP": "/Guadeloupe", 
 "Chicago, United States": "/United+States/Illinois/Chicago", 
 "Guadalcanal, Solomon Islands": "/Solomon+Islands/Guadalcanal", 
 "Cambridge Bay, Canada": "/Canada/Nunavut/Cambridge+Bay", 
 "Harare, Zimbabwe": "/Zimbabwe/Harare/Harare", 
 "Kerguelen, French Southern Territories": "/French+Southern+Territories", 
 "Chuuk, Micronesia": "/Federated+States+of+Micronesia/Chuuk", 
 "Podgorica, Montenegro": "/Montenegro/Podgorica/Podgorica", 
 "Thunder Bay, Canada": "/Canada/Ontario/Thunder+Bay", 
 "St Lucia, Saint Lucia": "/St.+Lucia", 
 "Mawson, Antarctica": "/Antarctica", 
 "San Juan, Argentina": "/Argentina/Santiago+del+Estero/San+Juan", 
 "Perth, Australia": "/Australia/Western+Australia/Perth", 
 "Maputo, Mozambique": "/Mozambique/Maputo/Maputo", 
 "Ushuaia, Argentina": "/Argentina/Tierra+del+Fuego/Ushuaia", 
 "Johannesburg, South Africa": "/South+Africa/Gauteng/Johannesburg", 
 "Niue, NU": "/Italy/Sardinia", 
 "San Luis, Argentina": "/Argentina/San+Luis/San+Luis", 
 "Matamoros, Mexico": "/Mexico/Chihuahua/Villa+Matamoros", 
 "Maldives, MV": "/Maldives", 
 "Taipei, Taiwan": "/Taiwan/Taipei+City/%E5%8F%B0%E5%8C%97%E5%B8%82", 
 "Rainy River, Canada": "/Canada/Ontario", 
 "Kuala Lumpur, Malaysia": "/Malaysia/Kuala+Lumpur/Kuala+Lumpur", 
 "Sofia, Bulgaria": "/Bulgaria/Sofiya-Grad/Sofia", 
 "Anchorage, United States": "/United+States/Alaska/Anchorage", 
 "Winnipeg, Canada": "/Canada/Manitoba/Winnipeg", 
 "Ndjamena, Chad": "/Chad/Ville+de+N%27Djamena/N%27Djamena", 
 "Paris, France": "/France/Ile-de-France/Paris", 
 "Noronha, Brazil": "/Brazil", 
 "Bahia Banderas, Mexico": "/M%C3%A9xico/Chihuahua/Banderas", 
 "Panama, PA": "/Panama/Panama/Ciudad+de+Panam%C3%A1", 
 "Rankin Inlet, Canada": "/Canada/Nunavut/Rankin+Inlet", 
 "Kashgar, China": "/China/Xinjiang/%E5%96%80%E4%BB%80%E5%B8%82", 
 "Jerusalem, Israel": "/Israel/Yerushalayim/Jerusalem", 
 "Syowa, Antarctica": "/Antarctica", 
 "Stockholm, Sweden": "/Sweden/Stockholm/Stockholm", 
 "El Salvador, SV": "/El+Salvador", 
 "Reunion, RE": "/Reunion/Arrondissement+of+Saint-Denis/R%C3%A9union", 
 "Martinique, MQ": "/Martinique", 
 "Sarajevo, Bosnia and Herzegovina": "/Bosnia+and+Herzegovina/Federacija+Bosne+I+Hercegovine/Sarajevo", 
 "Oral, Kazakhstan": "/Kazakhstan/Batys+Qazaqstan/Oral", 
 "Kaliningrad, Russia": "/Russia/Kaliningradskaya+Oblast/Kaliningrad", 
 "Nassau, Bahamas": "/The+Bahamas/New+Providence/Nassau", 
 "Tokyo, Japan": "/Japan/Tokyo+Prefecture/%E6%9D%B1%E4%BA%AC", 
 "Tahiti, French Polynesia": "/French+Polynesia/Windward+Islands", 
 "Wallis, Wallis and Futuna": "/Wallis+and+Futuna", 
 "Malabo, Equatorial Guinea": "/Equatorial+Guinea/Bioko+Norte/Malabo", 
 "Zurich, Switzerland": "/Switzerland/Canton+of+Zurich/Z%C3%BCrich", 
 "Vilnius, Lithuania": "/Lithuania/Vilnius+County/Vilnius", 
 "Gaborone, Botswana": "/Botswana/South-East/Gaborone", 
 "Jujuy, Argentina": "/Argentina/Jujuy", 
 "Dili, East Timor": "/East+Timor/Dili/Dili", 
 "Bermuda, BM": "/Bermuda", 
 "Vatican, VA": "/Italy/Lombardy", 
 "New Salem, North Dakota": "/United+States/North+Dakota/New+Salem", 
 "Mendoza, Argentina": "/Argentina/Mendoza/Mendoza", 
 "Muscat, Oman": "/Oman/Masqat/Muscat", 
 "Godthab, Greenland": "/Greenland/Vestgronland/Godth%C3%A5b", 
 "Yekaterinburg, Russia": "/Russia/Sverdlovskaya+Oblast/Yekaterinburg", 
 "St Kitts, Saint Kitts and Nevis": "/Saint+Kitts+and+Nevis", 
 "Monrovia, Liberia": "/Liberia/Monrovia/Monrovia", 
 "Madrid, Spain": "/Spain/Madrid/Madrid", 
 "Grenada, GD": "/Grenada", 
 "Vientiane, Laos": "/Laos/Viangchan/Vientiane", 
 "Anguilla, AI": "/Anguilla", 
 "Efate, Vanuatu": "/Vanuatu/Shefa", 
 "Scoresbysund, Greenland": "/Gr%C3%B8nland/Ostgronland/Scoresbysund", 
 "Gaza, Palestinian Territory": "/Palestinian+Occupied+Territories/Gaza/Gaza+City", 
 "Kuching, Malaysia": "/Malaysia/Sarawak/Kuching", 
 "Rio Gallegos, Argentina": "/Argentina/Santa+Cruz/R%C3%ADo+Gallegos", 
 "Asuncion, Paraguay": "/Paraguay/Asunci%C3%B3n/Asunci%C3%B3n", 
 "Amsterdam, Netherlands": "/Netherlands/North+Holland/Amsterdam", 
 "Bangui, Central African Republic": "/Central+African+Republic/Bangui/Bangui", 
 "Pitcairn, PN": "/Pitcairn+Islands", 
 "Lubumbashi, Democratic Republic of the Congo": "/Democratic+Republic+of+Congo/Katanga/Lubumbashi", 
 "Miquelon, Saint Pierre and Miquelon": "/Saint+Pierre+and+Miquelon/Miquelon-Langlade", 
 "Thimphu, Bhutan": "/Bhutan/Thimphu/Thimphu", 
 "Lisbon, Portugal": "/Portugal/Lisbon/Lisboa", 
 "Pontianak, Indonesia": "/Indonesia/West+Kalimantan/Pontianak", 
 "Berlin, Germany": "/Germany/Berlin/Berlin", 
 "Mauritius, MU": "/Mauritius", 
 "Yellowknife, Canada": "/Canada/Northwest+Territories/Yellowknife", 
 "Amman, Jordan": "/Jordan/%27Amman/Amman", 
 "Omsk, Russia": "/Russia/Omskaya+Oblast/Omsk", 
 "Glace Bay, Canada": "/Canada/Nova+Scotia/Sydney/Glace+Bay", 
 "Faroe, Faroe Islands": "/Faroe+Islands", 
 "Campo Grande, Brazil": "/Brazil/Mato+Grosso+do+Sul/Campo+Grande/in-Rio+Brilhante", 
 "Regina, Canada": "/Canada/Saskatchewan/Regina", 
 "Pago Pago, American Samoa": "/American+Samoa/Eastern/Pago+Pago", 
 "El Aaiun, Western Sahara": "/Western+Sahara/Sakia+El+Hamra/Laayoune", 
 "Bratislava, Slovakia": "/Slovakia/Bratislavsky/Bratislava", 
 "Qatar, QA": "/Qatar", 
 "Djibouti, DJ": "/Djibouti", 
 "Pangnirtung, Canada": "/Canada/Nunavut/Pangnirtung", 
 "Comoro, Comoros": "/Comoros", 
 "Puerto Rico, PR": "/Puerto+Rico", 
 "Pyongyang, North Korea": "/North+Korea/P%C2%B4yongyang-si/Pyongyang", 
 "Bogota, Colombia": "/Colombia/Distrito+Especial/Bogot%C3%A1", 
 "Fortaleza, Brazil": "/Brazil/Ceara/Fortaleza", 
 "Iqaluit, Canada": "/Canada/Nunavut/Iqaluit", 
 "Freetown, Sierra Leone": "/Sierra+Leone/Western+Area/Freetown", 
 "Kuwait, KW": "/Kuwait", 
 "Casey, Antarctica": "/Antarctica", 
 "Makassar, Indonesia": "/Indonesia/South+Sulawesi/Ujungpandang", 
 "Sydney, Australia": "/Australia/New+South+Wales/Sydney", 
 "Majuro, Marshall Islands": "/Marshall+Islands/Majuro/Majuro", 
 "Cuiaba, Brazil": "/Brazil/Mato+Grosso/Cuiab%C3%A1", 
 "Irkutsk, Russia": "/Russia/Irkutskaya+Oblast/Irkutsk", 
 "Midway, United States Minor Outlying Islands": "/United+States+Minor+Outlying+Islands", 
 "Bahrain, BH": "/Bahrain", 
 "Chagos, British Indian Ocean Territory": "/British+Indian+Ocean+Territory", 
 "Bamako, Mali": "/Mali/Bamako/Bamako", 
 "Mbabane, Swaziland": "/Swaziland/Hhohho/Mbabane", 
 "Beulah, North Dakota": "/United+States/North+Dakota/Beulah", 
 "Samara, Russia": "/Russia/Samarskaya+Oblast/Samara", 
 "Halifax, Canada": "/Canada/Nova+Scotia/Halifax", 
 "Kamchatka, Russia": "/Russia", 
 "Bujumbura, Burundi": "/Burundi/Bujumbura+Mairie/Bujumbura", 
 "Rome, Italy": "/Italy/Lazio/Roma", 
 "Phoenix, United States": "/United+States/Arizona/Phoenix", 
 "Hebron, Palestinian Territory": "/Palestinian+Occupied+Territories/West+Bank/Hebron", 
 "Baku, Azerbaijan": "/Azerbaijan/Baki/Baku", 
 "Jakarta, Indonesia": "/Indonesia/DKI+Jakarta/Jakarta", 
 "San Marino, SM": "/San+Marino/San+Marino/San+Marino", 
 "Catamarca, Argentina": "/Argentina/Catamarca/Catamarca", 
 "Dushanbe, Tajikistan": "/Tajikistan/Karategin/Dushanbe", 
 "Montreal, Canada": "/Canada/Quebec/Montr%C3%A9al", 
 "Santo Domingo, Dominican Republic": "/Dominican+Republic/Distrito+Nacional/Santo+Domingo", 
 "Boa Vista, Brazil": "/Brazil/Pernambuco/Recife/Boa+Vista", 
 "Zagreb, Croatia": "/Croatia/Grad+Zagreb/Zagreb", 
 "Nouakchott, Mauritania": "/Mauritania/Nouakchott/Nouakchott", 
 "Hovd, Mongolia": "/Mongolia/Hovd/Dund-Us", 
 "Bissau, Guinea-Bissau": "/Guin%C3%A9-Bissau/Bissau/Bissau", 
 "Algiers, Algeria": "/Algeria/Alger/Algiers", 
 "South Pole, Antarctica": "/Antarctica", 
 "Havana, Cuba": "/Cuba/Ciudad+de+la+Habana/La+Habana", 
 "Vaduz, Liechtenstein": "/Liechtenstein/Vaduz/Vaduz", 
 "Barbados, BB": "/Barbados", 
 "Easter, Chile": "/Chile", 
 "Swift Current, Canada": "/Canada/Saskatchewan/Swift+Current", 
 "Whitehorse, Canada": "/Canada/Yukon+Territory/Whitehorse", 
 "Chisinau, Moldova": "/Moldova/Chisinau/Chi%C5%A3inau", 
 "Funafuti, Tuvalu": "/Tuvalu/Funafuti/Funafuti", 
 "Aruba, AW": "/Aruba", 
 "Bishkek, Kyrgyzstan": "/Kyrgyzstan/Bishkek/Bishkek", 
 "Managua, Nicaragua": "/Nicaragua/Managua/Managua", 
 "Brisbane, Australia": "/Australia/Queensland/Brisbane", 
 "Wake, United States Minor Outlying Islands": "/United+States+Minor+Outlying+Islands", 
 "Stanley, Falkland Islands": "/Falkland+Islands/East+Falkland/Stanley", 
 "Kiritimati, Kiribati": "/Kiribati", 
 "Rio Branco, Brazil": "/Brazil/Acre/Rio+Branco/in-Rio+Branco", 
 "Belize, BZ": "/Belize/Belize/Belize+City", 
 "Vevay, Indiana": "/United+States/Indiana/Vevay", 
 "Cairo, Egypt": "/Al-Misr/Al+Qahirah/Cairo", 
 "Krasnoyarsk, Russia": "/Russia/Krasnoyarskiy+Kray/Krasnoyarsk", 
 "Luxembourg, LU": "/Luxembourg/Luxemburg/Ville+de+Luxembourg", 
 "Shiprock, United States": "/United+States/New+Mexico/Shiprock", 
 "Tijuana, Mexico": "/Mexico/Baja+California/Tijuana", 
 "St Thomas, U.S. Virgin Islands": "/US+Virgin+Islands/Saint+Thomas+Island", 
 "Brunei, BN": "/Brunei/Brunei-Muara/Bandar+Seri+Begawan", 
 "Bahia, Brazil": "/Brazil/Bahia", 
 "La Paz, Bolivia": "/Bolivia/La+Paz/La+Paz", 
 "Mahe, Seychelles": "/Seychelles/English+River/Victoria", 
 "Aqtau, Kazakhstan": "/Kazakhstan/Mangghystau/Aqtau", 
 "Lagos, Nigeria": "/Nigeria/Lagos/Lagos", 
 "Kampala, Uganda": "/Uganda/Kampala/Kampala", 
 "Dubai, United Arab Emirates": "/United+Arab+Emirates/Dubai/Dubai", 
 "Andorra, AD": "/Andorra/Andorra+la+Vella/Andorra+la+Vella", 
 "Merida, Mexico": "/Mexico/Yucatan/M%C3%A9rida", 
 "Budapest, Hungary": "/Hungary/Budapest/Budapest", 
 "Dawson, Canada": "/Canada/Yukon+Territory/Dawson", 
 "Boise, United States": "/United+States/Idaho/Boise", 
 "Reykjavik, Iceland": "/Iceland/Reykjavik/Reykjav%C3%ADk", 
 "Niamey, Niger": "/Niger/Niamey/Niamey", 
 "Longyearbyen, Svalbard and Jan Mayen": "/Svalbard+and+Jan+Mayen/Svalbard/Longyearbyen", 
 "Inuvik, Canada": "/Canada/Northwest+Territories/Inuvik", 
 "Juba, South Sudan": "/Sudan/Bahr+al+Jabal/Juba", 
 "Grand Turk, Turks and Caicos Islands": "/Turks+and+Caicos+Islands/Gand+Turk/Grand+Turk", 
 "Magadan, Russia": "/Russia/Magadanskaya+Oblast/Magadan", 
 "Sakhalin, Russia": "/Russia/Sakhalinskaya+Oblast", 
 "Ouagadougou, Burkina Faso": "/Burkina+Faso/Kadiogo/Ouagadougou", 
 "Vincennes, Indiana": "/United+States/Indiana/Vincennes", 
 "Tegucigalpa, Honduras": "/Honduras/Francisco+Moraz%C3%A1n/Tegucigalpa", 
 "Santiago, Chile": "/Chile/Santiago+Metropolitan+Region/Santiago", 
 "Paramaribo, Suriname": "/Suriname/Paramaribo/Paramaribo", 
 "Nauru, NR": "/Nauru", 
 "Port of Spain, Trinidad and Tobago": "/Trinidad+and+Tobago/Port+of+Spain/Port+of+Spain", 
 "Bucharest, Romania": "/Romania/Bucuresti/Bucure%C5%9Fti", 
 "Aqtobe, Kazakhstan": "/Kazakhstan/Aqtobe/Aqtobe", 
 "Volgograd, Russia": "/Russia/Volgogradskaya+Oblast/Volgograd", 
 "Marigot, Saint Martin": "/Saint-Martin/Marigot", 
 "Kinshasa, Democratic Republic of the Congo": "/Democratic+Republic+of+Congo/Kinshasa/Kinshasa", 
 "Tripoli, Libya": "/Libya/Tsarrbuus/Tripoli", 
 "Edmonton, Canada": "/Canada/Alberta/Edmonton", 
 "Lower Princes, Sint Maarten": "/Netherlands+Antilles/St.+Maarten", 
 "Juneau, United States": "/United+States/Alaska/Juneau", 
 "Porto Velho, Brazil": "/Brazil/Rondonia/P%C3%B4rto+Velho/in-Porto+Velho", 
 "Dawson Creek, Canada": "/Canada/British+Columbia/Dawson+Creek", 
 "Ljubljana, Slovenia": "/Slovenia/Ljubljana/Ljubljana", 
 "Tucuman, Argentina": "/Argentina/Tucuman/Tucum%C3%A1n", 
 "Prague, Czech Republic": "/Czech+Republic/Hlavni+mesto+Praha/Praha", 
 "Winamac, Indiana": "/United+States/Indiana/Winamac", 
 "Vancouver, Canada": "/Canada/British+Columbia/Vancouver", 
 "Lima, Peru": "/Per%C3%BA/Lima+Metropolitan+Area/Lima", 
 "Helsinki, Finland": "/Finland/Southern+Finland/Helsinki", 
 "Asmara, Eritrea": "/Eritrea/Maekel/Asmara", 
 "Vostok, Antarctica": "/Antarctica", 
 "Galapagos, Ecuador": "/Ecuador/Galapagos", 
 "Anadyr, Russia": "/Russia/Chukotskiy+Avtonomnyy+Okrug/Anadyr%27", 
 "Johnston, United States Minor Outlying Islands": "/United+States+Minor+Outlying+Islands", 
 "Fakaofo, Tokelau": "/Tokelau/Fakaofo", 
 "Apia, Samoa": "/Samoa/Tuamasaga/Apia", 
 "St Helena, Saint Helena": "/United+States/Nebraska", 
 "Santa Isabel, Mexico": "/M%C3%A9xico/Campeche/Santa+Isabel", 
 "Nome, United States": "/United+States/Alaska/Nome", 
 "Yakutat, United States": "/United+States/Alaska/Yakutat", 
 "Moncton, Canada": "/Canada/New+Brunswick/Moncton", 
 "Monterrey, Mexico": "/Mexico/Nuevo+Leon/Monterrey", 
 "Minsk, Belarus": "/Belarus/Minsk/Minsk", 
 "South Georgia, South Georgia and the South Sandwich Islands": "/South+Georgia+and+the+South+Sandwich+Islands", 
 "Samarkand, Uzbekistan": "/Uzbekistan/Samarqand/Samarqand", 
 "Manila, Philippines": "/Philippines/National+Capital+Region/Manila", 
 "Kiev, Ukraine": "/Ukraine/Kiev+City+Municipality/Kiev", 
 "Cape Verde, CV": "/Cape+Verde", 
 "Harbin, China": "/China/Heilongjiang/%E5%93%88%E5%B0%94%E6%BB%A8", 
 "Nicosia, Cyprus": "/Cyprus/Cyprus+TRNC", 
 "Vienna, Austria": "/Austria/Vienna/Wien", 
 "Urumqi, China": "/China/Xinjiang/%E4%B9%8C%E9%B2%81%E6%9C%A8%E9%BD%90%E5%B8%82", 
 "Maceio, Brazil": "/Brazil/Alagoas/Macei%C3%B3", 
 "Shanghai, China": "/China/Shanghai/%E4%B8%8A%E6%B5%B7%E5%B8%82", 
 "Davis, Antarctica": "/Antarctica", 
 "Hobart, Australia": "/Australia/Tasmania/Hobart", 
 "Mogadishu, Somalia": "/Somalia/Banaadir/Mogadishu", 
 "Knox, Indiana": "/United+States/Indiana/Knox/in-Starke", 
 "Choibalsan, Mongolia": "/Mongolia/Dornod/Choybalsan", 
 "Vladivostok, Russia": "/Russia/Primorskiy+Kray/Vladivostok", 
 "Noumea, New Caledonia": "/New+Caledonia/Sud/Noum%C3%A9a", 
 "Los Angeles, United States": "/United+States/California/Los+Angeles", 
 "Melbourne, Australia": "/Australia/Victoria/Melbourne", 
 "Detroit, United States": "/United+States/Michigan/Detroit", 
 "Libreville, Gabon": "/Gabon/Estuaire/Libreville", 
 "Gibraltar, GI": "/Gibraltar/Gibraltar", 
 "Damascus, Syria": "/Syria/Dimashq/Damascus", 
 "Singapore, SG": "/Singapore/Central+Singapore/Singapore", 
 "Monaco, MC": "/Monaco/La+Condamine/Monaco-Ville", 
 "Sao Paulo, Brazil": "/Brazil/Sao+Paulo/S%C3%A3o+Paulo/in-S%C3%A3o+Paulo", 
 "Lusaka, Zambia": "/Zambia/Lusaka/Lusaka", 
 "Antigua, Antigua and Barbuda": "/Antigua+and+Barbuda", 
 "Mexico City, Mexico": "/Mexico/Distrito+Federal/Ciudad+de+M%C3%A9xico", 
 "Chihuahua, Mexico": "/Mexico/Chihuahua/Chihuahua", 
 "Santarem, Brazil": "/Brazil/Para/Santar%C3%A9m/in-Santar%C3%A9m", 
 "Brazzaville, Republic of the Congo": "/R%C3%A9publique+du+Congo/Brazzaville/Brazzaville", 
 "Tbilisi, Georgia": "/Georgia/T%C2%B4bilisi/Tbilisi", 
 "Buenos Aires, Argentina": "/Argentina/Autonomous+City+of+Buenos+Aires/Buenos+Aires", 
 "Denver, United States": "/United+States/Colorado/Denver", 
 "Abidjan, Ivory Coast": "/Ivory+Coast/Lagunes/Abidjan", 
 "Auckland, New Zealand": "/New+Zealand/Auckland/Auckland", 
 "Almaty, Kazakhstan": "/Kazakhstan/Almaty/Almaty", 
 "Tashkent, Uzbekistan": "/Uzbekistan/Toshkent/Tashkent", 
 "Resolute, Canada": "/Canada/Nunavut/Resolute", 
 "Ojinaga, Mexico": "/Mexico/Chihuahua/Ojinaga", 
 "Costa Rica, CR": "/Costa+Rica", 
 "Salta, Argentina": "/Argentina/Salta/Salta", 
 "Ashgabat, Turkmenistan": "/Turkmenistan/Ashkhabad/Ashgabat", 
 "Moscow, Russia": "/Russia/Moskva/Moscow", 
 "Guam, GU": "/Guam", 
 "Toronto, Canada": "/Canada/Ontario/Toronto", 
 "Windhoek, Namibia": "/Namibia/Khomas/Windhoek", 
 "Palau, PW": "/Palau", 
 "Guayaquil, Ecuador": "/Ecuador/Guayas/Guayaquil", 
 "Enderbury, Kiribati": "/Kiribati", 
 "Madeira, Portugal": "/Portugal/Madeira", 
 "Currie, Australia": "/Australia/Tasmania/Currie", 
 "Goose Bay, Canada": "/Canada/Newfoundland+and+Labrador/Happy+Valley-Goose+Bay", 
 "Warsaw, Poland": "/Poland/Masovian/Warszawa", 
 "Jayapura, Indonesia": "/Indonesia/Papua/Jayapura", 
 "Jamaica, JM": "/Jamaica", 
 "London, United Kingdom": "/United+Kingdom/England/London", 
 "Seoul, South Korea": "/South+Korea/Seoul/%EC%84%9C%EC%9A%B8", 
 "Blanc-Sablon, Canada": "/Canada/Qu%C3%A9bec/Blanc-Sablon", 
 "Zaporozhye, Ukraine": "/Ukraine/Zaporizhia+Oblast/Zaporizhzhya", 
 "Macau, Macao": "/Macau/Macau", 
 "Lome, Togo": "/Togo/Maritime+Region/Lom%C3%A9", 
 "Dakar, Senegal": "/Senegal/Dakar/Dakar", 
 "Dublin, Ireland": "/Ireland/Dublin/Dublin", 
 "Malta, MT": "/United+States/Montana/Malta", 
 "Khartoum, Sudan": "/Sudan/Al+Khartum/Khartoum", 
 "Rothera, Antarctica": "/Antarctica", 
 "Tirane, Albania": "/Albania/Tiran%C3%AB/Tiran%C3%AB", 
 "Metlakatla, United States": "/United+States/Alaska/Metlakatla", 
 "Bangkok, Thailand": "/Thailand/Bangkok/Bangkok", 
 "Christmas, Christmas Island": "/Christmas+Island", 
 "Baghdad, Iraq": "/Iraq/Baghdad/Baghdad", 
 "Yakutsk, Russia": "/Russia/Sakha/Yakutsk", 
 "Maseru, Lesotho": "/Lesotho/Maseru/Maseru", 
 "Porto-Novo, Benin": "/B%C3%A9nin/Oueme/Porto-Novo", 
 "Accra, Ghana": "/Ghana/Greater+Accra/Accra", 
 "Guyana, GY": "/Guyana", 
 "Novosibirsk, Russia": "/Russia/Novosibirskaya+Oblast/Novosibirsk", 
 "Conakry, Guinea": "/Guinea/Conakry/Conakry", 
 "Isle of Man, IM": "/United+Kingdom/Isle+of+Man", 
 "Dhaka, Bangladesh": "/Bangladesh/Dhaka/Dhaka", 
 "Nipigon, Canada": "/Canada/Ontario/Nipigon", 
 "Curacao, Cura\u00e7ao": "/Netherlands+Antilles/Curacao", 
 "St Vincent, Saint Vincent and the Grenadines": "/Saint+Vincent+and+the+Grenadines", 
 "Istanbul, Turkey": "/Turkey/Istanbul/%C4%B0stanbul", 
 "Guatemala, GT": "/Guatemala/Guatemala/Ciudad+de+Guatemala"
};
