# Generates tz.js from time zone csv files
# get latest files from http://timezonedb.com/download
import csv,json,time,os
now = int(time.time())
zonerows = csv.reader(file("zone.csv"))
zones = {}
for r in zonerows:
  # zones[int(r[0])] = {"name":r[2].split('/')[-1].replace('_',' ')}
  zones[int(r[0])] = {"name":r[2].replace('_',' ')}
timezonerows = csv.reader(file("timezone.csv"))
for r in timezonerows:
  code = int(r[0])
  if not zones.has_key(code):
    continue
  starttime = int(r[2])
  offs = int(r[3])
  if offs < 0:
    offs += 60*60*24
  d = zones[code]
  if starttime<now and (not d.has_key("starttime") or d["starttime"]<starttime):
    d["starttime"] = starttime
    d["offs"] = offs
offsdict = {}
for k in zones:
  d = zones[k]
  if d["offs"]%3600: # One a dem funkey time zones
    continue # Let's not confuse the user :)
  offsdict[d["offs"]] = offsdict.get(d["offs"],[])+[d["name"]]
res = sorted([[k,sorted(offsdict[k])] for k in offsdict],key=lambda x:-x[0])
js = file("tz.js","w")
js.write("// Generated by mk420tz.py - see https://github.com/thedod/global420\n")
js.write("// Data source: http://timezonedb.com/files/timezonedb.csv.zip\n")
js.write("//              (version: {0})\n".format(time.ctime(os.stat("zone.csv").st_mtime)))
js.write("window.timezones = ")
json.dump(res,js,indent=1)
js.close()
